### PR TITLE
advanced the readme file

### LINKED ISSUE #10: update readme file
hey can i work on this?

### PR DESCRIPTION
**Pull request by Janhvi52**
closes #10 
you can have a look at it and merge the same,thankyou!

### CODE REVIEW

**Comment by YadnikaDabhade** [comment]
@Janhvi52 you must add the screenshot of your work

**Comment by Janhvi52** [comment]
> @Janhvi52 you must add the screenshot of your work



> @Janhvi52 you must add the screenshot of your work

Screenshot (118)

i've added the or options to readme file in order to make it more readable and useful for all kinds of users!

**Comment by YadnikaDabhade** [comment]
@Janhvi52  enhance the readme file , try to make it more attractive

**Comment by Janhvi52** [comment]
> @Janhvi52 enhance the readme file , try to make it more attractive

Screenshot (120)

i've added some screenshots of your website and some fascinating words to allure the customers and students to work upon!
hope u like it now!

**Comment by Janhvi52** [comment]
> > @Janhvi52 enhance the readme file , try to make it more attractive
> 
> Screenshot (120)
> 
> i've added some screenshots of your website and some fascinating words to allure the customers and students to work upon! hope u like it now!

@YadnikaDabhade can check now!

**Comment by Janhvi52** [comment]
> > > @Janhvi52 enhance the readme file , try to make it more attractive
> > 
> > 
> > Screenshot (120)
> > i've added some screenshots of your website and some fascinating words to allure the customers and students to work upon! hope u like it now!
> 
> @YadnikaDabhade can check now!

**Pull request merged**
